'use strict';
const GENKI2_VOCAB = [
  { lesson: 13, japanese: "あげる", reading: "あげる", english: "to give (to others)", pos: "verb-ru" },
  { lesson: 13, japanese: "くれる", reading: "くれる", english: "to give (to me/us)", pos: "verb-ru" },
  { lesson: 13, japanese: "もらう", reading: "もらう", english: "to receive", pos: "verb-u" },
  { lesson: 13, japanese: "かう", reading: "かう", english: "to buy", pos: "verb-u" },
  { lesson: 13, japanese: "おしえる", reading: "おしえる", english: "to teach; to inform", pos: "verb-ru" },
  { lesson: 13, japanese: "おばさん", reading: "おばさん", english: "aunt; middle-aged woman", pos: "noun" },
  { lesson: 13, japanese: "おじさん", reading: "おじさん", english: "uncle; middle-aged man", pos: "noun" },
  { lesson: 13, japanese: "おば", reading: "おば", english: "aunt (own family)", pos: "noun" },
  { lesson: 13, japanese: "おじ", reading: "おじ", english: "uncle (own family)", pos: "noun" },
  { lesson: 13, japanese: "りょうしん", reading: "りょうしん", english: "parents", pos: "noun" },
  { lesson: 13, japanese: "彼女", reading: "かのじょ", english: "girlfriend; she", pos: "noun" },
  { lesson: 13, japanese: "彼", reading: "かれ", english: "boyfriend; he", pos: "noun" },
  { lesson: 13, japanese: "かれし", reading: "かれし", english: "boyfriend", pos: "noun" },
  { lesson: 13, japanese: "ともだち", reading: "ともだち", english: "friend", pos: "noun" },
  { lesson: 13, japanese: "クラスメート", reading: "クラスメート", english: "classmate", pos: "noun" },
  { lesson: 13, japanese: "かみ", reading: "かみ", english: "hair", pos: "noun" },
  { lesson: 13, japanese: "てぶくろ", reading: "てぶくろ", english: "gloves", pos: "noun" },
  { lesson: 13, japanese: "マフラー", reading: "マフラー", english: "scarf; muffler", pos: "noun" },
  { lesson: 13, japanese: "チョコレート", reading: "チョコレート", english: "chocolate", pos: "noun" },
  { lesson: 13, japanese: "ぬいぐるみ", reading: "ぬいぐるみ", english: "stuffed animal", pos: "noun" },
  { lesson: 13, japanese: "ピアス", reading: "ピアス", english: "pierced earrings", pos: "noun" },
  { lesson: 13, japanese: "かちょう", reading: "かちょう", english: "section chief; manager", pos: "noun" },
  { lesson: 13, japanese: "しゃちょう", reading: "しゃちょう", english: "company president", pos: "noun" },
  { lesson: 13, japanese: "じかん", reading: "じかん", english: "time", pos: "noun" },
  { lesson: 13, japanese: "クリスマス", reading: "クリスマス", english: "Christmas", pos: "noun" },
  { lesson: 13, japanese: "バレンタインデー", reading: "バレンタインデー", english: "Valentine's Day", pos: "noun" },
  { lesson: 13, japanese: "はやい", reading: "はやい", english: "early", pos: "i-adj" },
  { lesson: 13, japanese: "ほしい", reading: "ほしい", english: "wanted; desired", pos: "i-adj" },
  { lesson: 13, japanese: "もう", reading: "もう", english: "already; anymore", pos: "adverb" },
  { lesson: 13, japanese: "まだ", reading: "まだ", english: "still; not yet", pos: "adverb" },
  { lesson: 13, japanese: "さっき", reading: "さっき", english: "a short while ago", pos: "adverb" },
  { lesson: 13, japanese: "じゃあ", reading: "じゃあ", english: "then; well then", pos: "conjunction" },
  { lesson: 13, japanese: "ぜひ", reading: "ぜひ", english: "by all means; certainly", pos: "adverb" },
  { lesson: 14, japanese: "うまれる", reading: "うまれる", english: "to be born", pos: "verb-ru" },
  { lesson: 14, japanese: "そだつ", reading: "そだつ", english: "to grow up", pos: "verb-u" },
  { lesson: 14, japanese: "りゅうがくする", reading: "りゅうがくする", english: "to study abroad", pos: "verb-irr" },
  { lesson: 14, japanese: "すむ", reading: "すむ", english: "to live (in); to reside", pos: "verb-u" },
  { lesson: 14, japanese: "はたらく", reading: "はたらく", english: "to work", pos: "verb-u" },
  { lesson: 14, japanese: "けっこんする", reading: "けっこんする", english: "to get married", pos: "verb-irr" },
  { lesson: 14, japanese: "ある", reading: "ある", english: "there is; to have (inanimate)", pos: "verb-u" },
  { lesson: 14, japanese: "いなか", reading: "いなか", english: "rural area; hometown; countryside", pos: "noun" },
  { lesson: 14, japanese: "まち", reading: "まち", english: "town; city", pos: "noun" },
  { lesson: 14, japanese: "しゅと", reading: "しゅと", english: "capital city", pos: "noun" },
  { lesson: 14, japanese: "こうがい", reading: "こうがい", english: "suburbs", pos: "noun" },
  { lesson: 14, japanese: "きせつ", reading: "きせつ", english: "season", pos: "noun" },
  { lesson: 14, japanese: "はる", reading: "はる", english: "spring", pos: "noun" },
  { lesson: 14, japanese: "なつ", reading: "なつ", english: "summer", pos: "noun" },
  { lesson: 14, japanese: "あき", reading: "あき", english: "autumn; fall", pos: "noun" },
  { lesson: 14, japanese: "ふゆ", reading: "ふゆ", english: "winter", pos: "noun" },
  { lesson: 14, japanese: "きおん", reading: "きおん", english: "temperature (air)", pos: "noun" },
  { lesson: 14, japanese: "ゆき", reading: "ゆき", english: "snow", pos: "noun" },
  { lesson: 14, japanese: "あめ", reading: "あめ", english: "rain", pos: "noun" },
  { lesson: 14, japanese: "かぜ", reading: "かぜ", english: "wind", pos: "noun" },
  { lesson: 14, japanese: "くも", reading: "くも", english: "cloud", pos: "noun" },
  { lesson: 14, japanese: "たてもの", reading: "たてもの", english: "building", pos: "noun" },
  { lesson: 14, japanese: "じんじゃ", reading: "じんじゃ", english: "Shinto shrine", pos: "noun" },
  { lesson: 14, japanese: "おてら", reading: "おてら", english: "temple", pos: "noun" },
  { lesson: 14, japanese: "びじゅつかん", reading: "びじゅつかん", english: "art museum", pos: "noun" },
  { lesson: 14, japanese: "どうぶつえん", reading: "どうぶつえん", english: "zoo", pos: "noun" },
  { lesson: 14, japanese: "こうえん", reading: "こうえん", english: "park", pos: "noun" },
  { lesson: 14, japanese: "にぎやか", reading: "にぎやか", english: "lively; bustling", pos: "na-adj" },
  { lesson: 14, japanese: "しずか", reading: "しずか", english: "quiet; peaceful", pos: "na-adj" },
  { lesson: 14, japanese: "べんり", reading: "べんり", english: "convenient", pos: "na-adj" },
  { lesson: 14, japanese: "ふべん", reading: "ふべん", english: "inconvenient", pos: "na-adj" },
  { lesson: 14, japanese: "ゆうめい", reading: "ゆうめい", english: "famous", pos: "na-adj" },
  { lesson: 14, japanese: "だいたい", reading: "だいたい", english: "mostly; generally; about", pos: "adverb" },
  { lesson: 14, japanese: "とくに", reading: "とくに", english: "especially; particularly", pos: "adverb" },
  { lesson: 15, japanese: "うんどうする", reading: "うんどうする", english: "to exercise", pos: "verb-irr" },
  { lesson: 15, japanese: "ダイエットする", reading: "ダイエットする", english: "to go on a diet", pos: "verb-irr" },
  { lesson: 15, japanese: "よやくする", reading: "よやくする", english: "to make a reservation", pos: "verb-irr" },
  { lesson: 15, japanese: "もうしこむ", reading: "もうしこむ", english: "to apply for", pos: "verb-u" },
  { lesson: 15, japanese: "やめる", reading: "やめる", english: "to quit; to stop", pos: "verb-ru" },
  { lesson: 15, japanese: "けんかする", reading: "けんかする", english: "to have a fight; to quarrel", pos: "verb-irr" },
  { lesson: 15, japanese: "にゅうがくする", reading: "にゅうがくする", english: "to enter a school", pos: "verb-irr" },
  { lesson: 15, japanese: "そつぎょうする", reading: "そつぎょうする", english: "to graduate", pos: "verb-irr" },
  { lesson: 15, japanese: "おもいだす", reading: "おもいだす", english: "to recall; to remember", pos: "verb-u" },
  { lesson: 15, japanese: "わかれる", reading: "わかれる", english: "to break up; to separate", pos: "verb-ru" },
  { lesson: 15, japanese: "こうこう", reading: "こうこう", english: "high school", pos: "noun" },
  { lesson: 15, japanese: "こうこうせい", reading: "こうこうせい", english: "high school student", pos: "noun" },
  { lesson: 15, japanese: "じどうしゃ", reading: "じどうしゃ", english: "automobile; car", pos: "noun" },
  { lesson: 15, japanese: "おかし", reading: "おかし", english: "sweets; candy; snack", pos: "noun" },
  { lesson: 15, japanese: "にっき", reading: "にっき", english: "diary", pos: "noun" },
  { lesson: 15, japanese: "ゆめ", reading: "ゆめ", english: "dream", pos: "noun" },
  { lesson: 15, japanese: "けいけん", reading: "けいけん", english: "experience", pos: "noun" },
  { lesson: 15, japanese: "きおく", reading: "きおく", english: "memory; recollection", pos: "noun" },
  { lesson: 15, japanese: "こどものころ", reading: "こどものころ", english: "when (I) was a child", pos: "expression" },
  { lesson: 15, japanese: "むかし", reading: "むかし", english: "old days; long ago; past", pos: "noun" },
  { lesson: 15, japanese: "ひさしぶり", reading: "ひさしぶり", english: "after a long time; long time no see", pos: "expression" },
  { lesson: 15, japanese: "すごい", reading: "すごい", english: "wow; amazing; terrible", pos: "i-adj" },
  { lesson: 15, japanese: "かなしい", reading: "かなしい", english: "sad", pos: "i-adj" },
  { lesson: 15, japanese: "うれしい", reading: "うれしい", english: "happy; glad", pos: "i-adj" },
  { lesson: 15, japanese: "なつかしい", reading: "なつかしい", english: "nostalgic; fondly remembered", pos: "i-adj" },
  { lesson: 15, japanese: "まじめ", reading: "まじめ", english: "serious; diligent; honest", pos: "na-adj" },
  { lesson: 15, japanese: "いちど", reading: "いちど", english: "once; one time", pos: "adverb" },
  { lesson: 15, japanese: "いつか", reading: "いつか", english: "sometime; someday", pos: "adverb" },
  { lesson: 15, japanese: "けっして〜ない", reading: "けっして〜ない", english: "never (with negative)", pos: "adverb" },
  { lesson: 15, japanese: "〜について", reading: "〜について", english: "about; concerning", pos: "particle" },
  { lesson: 16, japanese: "いしゃ", reading: "いしゃ", english: "medical doctor", pos: "noun" },
  { lesson: 16, japanese: "びょういん", reading: "びょういん", english: "hospital", pos: "noun" },
  { lesson: 16, japanese: "くすり", reading: "くすり", english: "medicine", pos: "noun" },
  { lesson: 16, japanese: "びょうき", reading: "びょうき", english: "illness; disease; sickness", pos: "noun" },
  { lesson: 16, japanese: "かぜ", reading: "かぜ", english: "cold (illness)", pos: "noun" },
  { lesson: 16, japanese: "ねつ", reading: "ねつ", english: "fever; temperature", pos: "noun" },
  { lesson: 16, japanese: "いたみ", reading: "いたみ", english: "pain; ache", pos: "noun" },
  { lesson: 16, japanese: "あたま", reading: "あたま", english: "head", pos: "noun" },
  { lesson: 16, japanese: "おなか", reading: "おなか", english: "stomach; belly", pos: "noun" },
  { lesson: 16, japanese: "のど", reading: "のど", english: "throat", pos: "noun" },
  { lesson: 16, japanese: "は", reading: "は", english: "tooth; teeth", pos: "noun" },
  { lesson: 16, japanese: "め", reading: "め", english: "eye", pos: "noun" },
  { lesson: 16, japanese: "みみ", reading: "みみ", english: "ear", pos: "noun" },
  { lesson: 16, japanese: "せなか", reading: "せなか", english: "back (of body)", pos: "noun" },
  { lesson: 16, japanese: "あし", reading: "あし", english: "leg; foot", pos: "noun" },
  { lesson: 16, japanese: "て", reading: "て", english: "hand; arm", pos: "noun" },
  { lesson: 16, japanese: "たいおん", reading: "たいおん", english: "body temperature", pos: "noun" },
  { lesson: 16, japanese: "けが", reading: "けが", english: "injury; wound", pos: "noun" },
  { lesson: 16, japanese: "はなみず", reading: "はなみず", english: "runny nose", pos: "noun" },
  { lesson: 16, japanese: "せき", reading: "せき", english: "cough", pos: "noun" },
  { lesson: 16, japanese: "さとう", reading: "さとう", english: "sugar", pos: "noun" },
  { lesson: 16, japanese: "たいちょう", reading: "たいちょう", english: "physical condition; health", pos: "noun" },
  { lesson: 16, japanese: "ストレス", reading: "ストレス", english: "stress", pos: "noun" },
  { lesson: 16, japanese: "いたい", reading: "いたい", english: "painful; hurts; sore", pos: "i-adj" },
  { lesson: 16, japanese: "かゆい", reading: "かゆい", english: "itchy", pos: "i-adj" },
  { lesson: 16, japanese: "おかしい", reading: "おかしい", english: "strange; funny; odd", pos: "i-adj" },
  { lesson: 16, japanese: "ひどい", reading: "ひどい", english: "terrible; severe; cruel", pos: "i-adj" },
  { lesson: 16, japanese: "ねる", reading: "ねる", english: "to sleep; to go to bed", pos: "verb-ru" },
  { lesson: 16, japanese: "やすむ", reading: "やすむ", english: "to rest; to be absent", pos: "verb-u" },
  { lesson: 16, japanese: "のむ", reading: "のむ", english: "to drink; to take (medicine)", pos: "verb-u" },
  { lesson: 16, japanese: "てんきんする", reading: "てんきんする", english: "to transfer (to another office)", pos: "verb-irr" },
  { lesson: 16, japanese: "ちゃんと", reading: "ちゃんと", english: "properly; regularly; neatly", pos: "adverb" },
  { lesson: 16, japanese: "もうすこし", reading: "もうすこし", english: "a little more", pos: "adverb" },
  { lesson: 16, japanese: "〜くらい", reading: "〜くらい", english: "about; approximately", pos: "particle" },
  { lesson: 17, japanese: "こどもたち", reading: "こどもたち", english: "children", pos: "noun" },
  { lesson: 17, japanese: "むすこ", reading: "むすこ", english: "son (own)", pos: "noun" },
  { lesson: 17, japanese: "むすめ", reading: "むすめ", english: "daughter (own)", pos: "noun" },
  { lesson: 17, japanese: "おこさん", reading: "おこさん", english: "child (someone else's)", pos: "noun" },
  { lesson: 17, japanese: "むすこさん", reading: "むすこさん", english: "son (someone else's)", pos: "noun" },
  { lesson: 17, japanese: "むすめさん", reading: "むすめさん", english: "daughter (someone else's)", pos: "noun" },
  { lesson: 17, japanese: "しゅじん", reading: "しゅじん", english: "husband (own)", pos: "noun" },
  { lesson: 17, japanese: "かない", reading: "かない", english: "wife (own)", pos: "noun" },
  { lesson: 17, japanese: "こまる", reading: "こまる", english: "to be in trouble; to be at a loss", pos: "verb-u" },
  { lesson: 17, japanese: "おこる", reading: "おこる", english: "to get angry", pos: "verb-u" },
  { lesson: 17, japanese: "しかる", reading: "しかる", english: "to scold", pos: "verb-u" },
  { lesson: 17, japanese: "なく", reading: "なく", english: "to cry", pos: "verb-u" },
  { lesson: 17, japanese: "わらう", reading: "わらう", english: "to laugh; to smile", pos: "verb-u" },
  { lesson: 17, japanese: "かたづける", reading: "かたづける", english: "to tidy up; to put in order", pos: "verb-ru" },
  { lesson: 17, japanese: "すてる", reading: "すてる", english: "to throw away; to discard", pos: "verb-ru" },
  { lesson: 17, japanese: "よごす", reading: "よごす", english: "to make dirty; to soil", pos: "verb-u" },
  { lesson: 17, japanese: "こわす", reading: "こわす", english: "to break; to destroy", pos: "verb-u" },
  { lesson: 17, japanese: "むだづかいする", reading: "むだづかいする", english: "to waste money", pos: "verb-irr" },
  { lesson: 17, japanese: "ちこくする", reading: "ちこくする", english: "to be late; to be tardy", pos: "verb-irr" },
  { lesson: 17, japanese: "さぼる", reading: "さぼる", english: "to skip; to play hooky", pos: "verb-u" },
  { lesson: 17, japanese: "けんきゅうする", reading: "けんきゅうする", english: "to research; to study", pos: "verb-irr" },
  { lesson: 17, japanese: "しつれい", reading: "しつれい", english: "impoliteness; rudeness", pos: "noun" },
  { lesson: 17, japanese: "うそ", reading: "うそ", english: "lie; falsehood", pos: "noun" },
  { lesson: 17, japanese: "ばかり", reading: "ばかり", english: "only; nothing but", pos: "particle" },
  { lesson: 17, japanese: "〜させる", reading: "〜させる", english: "causative suffix (make/let)", pos: "suffix" },
  { lesson: 17, japanese: "まず", reading: "まず", english: "first of all; to begin with", pos: "adverb" },
  { lesson: 17, japanese: "それに", reading: "それに", english: "besides; in addition", pos: "conjunction" },
  { lesson: 17, japanese: "あんなに", reading: "あんなに", english: "to that extent; like that", pos: "adverb" },
  { lesson: 17, japanese: "こんなに", reading: "こんなに", english: "to this extent; like this", pos: "adverb" },
  { lesson: 17, japanese: "そんなに", reading: "そんなに", english: "to that extent; so much (near listener)", pos: "adverb" },
  { lesson: 18, japanese: "りょこうする", reading: "りょこうする", english: "to travel", pos: "verb-irr" },
  { lesson: 18, japanese: "よむ", reading: "よむ", english: "to read", pos: "verb-u" },
  { lesson: 18, japanese: "ほめる", reading: "ほめる", english: "to praise; to compliment", pos: "verb-ru" },
  { lesson: 18, japanese: "おこなう", reading: "おこなう", english: "to carry out; to hold (an event)", pos: "verb-u" },
  { lesson: 18, japanese: "かむ", reading: "かむ", english: "to bite", pos: "verb-u" },
  { lesson: 18, japanese: "ふむ", reading: "ふむ", english: "to step on", pos: "verb-u" },
  { lesson: 18, japanese: "ぬすむ", reading: "ぬすむ", english: "to steal", pos: "verb-u" },
  { lesson: 18, japanese: "つかまえる", reading: "つかまえる", english: "to catch; to arrest", pos: "verb-ru" },
  { lesson: 18, japanese: "ころす", reading: "ころす", english: "to kill", pos: "verb-u" },
  { lesson: 18, japanese: "たてる", reading: "たてる", english: "to build; to establish", pos: "verb-ru" },
  { lesson: 18, japanese: "はつめいする", reading: "はつめいする", english: "to invent", pos: "verb-irr" },
  { lesson: 18, japanese: "はっけんする", reading: "はっけんする", english: "to discover", pos: "verb-irr" },
  { lesson: 18, japanese: "りょかん", reading: "りょかん", english: "Japanese inn", pos: "noun" },
  { lesson: 18, japanese: "ホテル", reading: "ホテル", english: "hotel", pos: "noun" },
  { lesson: 18, japanese: "パスポート", reading: "パスポート", english: "passport", pos: "noun" },
  { lesson: 18, japanese: "スーツケース", reading: "スーツケース", english: "suitcase", pos: "noun" },
  { lesson: 18, japanese: "みやげ", reading: "みやげ", english: "souvenir", pos: "noun" },
  { lesson: 18, japanese: "かいがい", reading: "かいがい", english: "overseas; abroad", pos: "noun" },
  { lesson: 18, japanese: "ひこうき", reading: "ひこうき", english: "airplane", pos: "noun" },
  { lesson: 18, japanese: "しんかんせん", reading: "しんかんせん", english: "Shinkansen; bullet train", pos: "noun" },
  { lesson: 18, japanese: "ふね", reading: "ふね", english: "ship; boat", pos: "noun" },
  { lesson: 18, japanese: "えき", reading: "えき", english: "train station", pos: "noun" },
  { lesson: 18, japanese: "くうこう", reading: "くうこう", english: "airport", pos: "noun" },
  { lesson: 18, japanese: "ちかてつ", reading: "ちかてつ", english: "subway", pos: "noun" },
  { lesson: 18, japanese: "バス", reading: "バス", english: "bus", pos: "noun" },
  { lesson: 18, japanese: "でんしゃ", reading: "でんしゃ", english: "train; electric train", pos: "noun" },
  { lesson: 18, japanese: "荷物", reading: "にもつ", english: "baggage; luggage", pos: "noun" },
  { lesson: 18, japanese: "チケット", reading: "チケット", english: "ticket", pos: "noun" },
  { lesson: 18, japanese: "かんこうきゃく", reading: "かんこうきゃく", english: "tourist; sightseer", pos: "noun" },
  { lesson: 18, japanese: "せかい", reading: "せかい", english: "world", pos: "noun" },
  { lesson: 18, japanese: "れきし", reading: "れきし", english: "history", pos: "noun" },
  { lesson: 18, japanese: "〜によって", reading: "〜によって", english: "by (agent in passive); depending on", pos: "particle" },
  { lesson: 19, japanese: "晴れる", reading: "はれる", english: "to become sunny; to clear up", pos: "verb-ru" },
  { lesson: 19, japanese: "曇る", reading: "くもる", english: "to become cloudy", pos: "verb-u" },
  { lesson: 19, japanese: "降る", reading: "ふる", english: "to fall (rain/snow)", pos: "verb-u" },
  { lesson: 19, japanese: "ふえる", reading: "ふえる", english: "to increase", pos: "verb-ru" },
  { lesson: 19, japanese: "へる", reading: "へる", english: "to decrease", pos: "verb-ru" },
  { lesson: 19, japanese: "かわる", reading: "かわる", english: "to change; to be different", pos: "verb-u" },
  { lesson: 19, japanese: "あつまる", reading: "あつまる", english: "to gather; to collect", pos: "verb-u" },
  { lesson: 19, japanese: "でかける", reading: "でかける", english: "to go out; to leave", pos: "verb-ru" },
  { lesson: 19, japanese: "きをつける", reading: "きをつける", english: "to be careful; to watch out", pos: "verb-ru" },
  { lesson: 19, japanese: "天気", reading: "てんき", english: "weather", pos: "noun" },
  { lesson: 19, japanese: "きこう", reading: "きこう", english: "climate", pos: "noun" },
  { lesson: 19, japanese: "台風", reading: "たいふう", english: "typhoon", pos: "noun" },
  { lesson: 19, japanese: "地震", reading: "じしん", english: "earthquake", pos: "noun" },
  { lesson: 19, japanese: "こうずい", reading: "こうずい", english: "flood", pos: "noun" },
  { lesson: 19, japanese: "かじ", reading: "かじ", english: "fire (destructive)", pos: "noun" },
  { lesson: 19, japanese: "じこ", reading: "じこ", english: "accident", pos: "noun" },
  { lesson: 19, japanese: "きけん", reading: "きけん", english: "danger; dangerous", pos: "na-adj" },
  { lesson: 19, japanese: "あんぜん", reading: "あんぜん", english: "safety; safe", pos: "na-adj" },
  { lesson: 19, japanese: "おおい", reading: "おおい", english: "many; a lot; much", pos: "i-adj" },
  { lesson: 19, japanese: "すくない", reading: "すくない", english: "few; a little; scarce", pos: "i-adj" },
  { lesson: 19, japanese: "暖かい", reading: "あたたかい", english: "warm", pos: "i-adj" },
  { lesson: 19, japanese: "涼しい", reading: "すずしい", english: "cool; refreshing", pos: "i-adj" },
  { lesson: 19, japanese: "寒い", reading: "さむい", english: "cold (weather)", pos: "i-adj" },
  { lesson: 19, japanese: "蒸し暑い", reading: "むしあつい", english: "hot and humid; muggy", pos: "i-adj" },
  { lesson: 19, japanese: "かんそうする", reading: "かんそうする", english: "to dry up; to become dry", pos: "verb-irr" },
  { lesson: 19, japanese: "ぜんぜん〜ない", reading: "ぜんぜん〜ない", english: "not at all (with negative)", pos: "adverb" },
  { lesson: 19, japanese: "もし〜たら", reading: "もし〜たら", english: "if (hypothetical)", pos: "conjunction" },
  { lesson: 19, japanese: "〜かもしれない", reading: "〜かもしれない", english: "might; maybe; possibly", pos: "expression" },
  { lesson: 19, japanese: "たぶん", reading: "たぶん", english: "probably; maybe", pos: "adverb" },
  { lesson: 19, japanese: "きっと", reading: "きっと", english: "surely; certainly", pos: "adverb" },
  { lesson: 20, japanese: "りょうりする", reading: "りょうりする", english: "to cook; to prepare food", pos: "verb-irr" },
  { lesson: 20, japanese: "作る", reading: "つくる", english: "to make; to cook", pos: "verb-u" },
  { lesson: 20, japanese: "切る", reading: "きる", english: "to cut", pos: "verb-u" },
  { lesson: 20, japanese: "混ぜる", reading: "まぜる", english: "to mix; to stir", pos: "verb-ru" },
  { lesson: 20, japanese: "炒める", reading: "いためる", english: "to stir-fry; to sauté", pos: "verb-ru" },
  { lesson: 20, japanese: "煮る", reading: "にる", english: "to boil; to simmer", pos: "verb-ru" },
  { lesson: 20, japanese: "焼く", reading: "やく", english: "to grill; to bake; to roast; to fry", pos: "verb-u" },
  { lesson: 20, japanese: "あげる", reading: "あげる", english: "to deep-fry", pos: "verb-ru" },
  { lesson: 20, japanese: "わかす", reading: "わかす", english: "to boil (water)", pos: "verb-u" },
  { lesson: 20, japanese: "ちらかす", reading: "ちらかす", english: "to scatter; to make a mess", pos: "verb-u" },
  { lesson: 20, japanese: "けす", reading: "けす", english: "to turn off; to extinguish", pos: "verb-u" },
  { lesson: 20, japanese: "つける", reading: "つける", english: "to turn on; to attach", pos: "verb-ru" },
  { lesson: 20, japanese: "りょうり", reading: "りょうり", english: "cooking; cuisine; dish", pos: "noun" },
  { lesson: 20, japanese: "ざいりょう", reading: "ざいりょう", english: "ingredients; materials", pos: "noun" },
  { lesson: 20, japanese: "レシピ", reading: "レシピ", english: "recipe", pos: "noun" },
  { lesson: 20, japanese: "なべ", reading: "なべ", english: "pot; pan", pos: "noun" },
  { lesson: 20, japanese: "フライパン", reading: "フライパン", english: "frying pan", pos: "noun" },
  { lesson: 20, japanese: "あぶら", reading: "あぶら", english: "oil; fat", pos: "noun" },
  { lesson: 20, japanese: "塩", reading: "しお", english: "salt", pos: "noun" },
  { lesson: 20, japanese: "醤油", reading: "しょうゆ", english: "soy sauce", pos: "noun" },
  { lesson: 20, japanese: "みそ", reading: "みそ", english: "miso (fermented soybean paste)", pos: "noun" },
  { lesson: 20, japanese: "さけ", reading: "さけ", english: "sake; rice wine", pos: "noun" },
  { lesson: 20, japanese: "みりん", reading: "みりん", english: "sweet rice wine (for cooking)", pos: "noun" },
  { lesson: 20, japanese: "す", reading: "す", english: "vinegar", pos: "noun" },
  { lesson: 20, japanese: "こしょう", reading: "こしょう", english: "pepper", pos: "noun" },
  { lesson: 20, japanese: "砂糖", reading: "さとう", english: "sugar", pos: "noun" },
  { lesson: 20, japanese: "にんじん", reading: "にんじん", english: "carrot", pos: "noun" },
  { lesson: 20, japanese: "たまねぎ", reading: "たまねぎ", english: "onion", pos: "noun" },
  { lesson: 20, japanese: "じゃがいも", reading: "じゃがいも", english: "potato", pos: "noun" },
  { lesson: 20, japanese: "とりにく", reading: "とりにく", english: "chicken (meat)", pos: "noun" },
  { lesson: 20, japanese: "ぎゅうにく", reading: "ぎゅうにく", english: "beef", pos: "noun" },
  { lesson: 20, japanese: "ぶたにく", reading: "ぶたにく", english: "pork", pos: "noun" },
  { lesson: 20, japanese: "まず", reading: "まず", english: "first; to begin with", pos: "adverb" },
  { lesson: 20, japanese: "つぎに", reading: "つぎに", english: "next; then", pos: "adverb" },
  { lesson: 20, japanese: "さいごに", reading: "さいごに", english: "finally; lastly", pos: "adverb" },
  { lesson: 21, japanese: "ダウンロードする", reading: "ダウンロードする", english: "to download", pos: "verb-irr" },
  { lesson: 21, japanese: "アップロードする", reading: "アップロードする", english: "to upload", pos: "verb-irr" },
  { lesson: 21, japanese: "クリックする", reading: "クリックする", english: "to click", pos: "verb-irr" },
  { lesson: 21, japanese: "メールする", reading: "メールする", english: "to send an email", pos: "verb-irr" },
  { lesson: 21, japanese: "でんわする", reading: "でんわする", english: "to make a phone call", pos: "verb-irr" },
  { lesson: 21, japanese: "なおす", reading: "なおす", english: "to fix; to repair; to correct", pos: "verb-u" },
  { lesson: 21, japanese: "こわれる", reading: "こわれる", english: "to break; to be broken", pos: "verb-ru" },
  { lesson: 21, japanese: "つかう", reading: "つかう", english: "to use", pos: "verb-u" },
  { lesson: 21, japanese: "さがす", reading: "さがす", english: "to search for; to look for", pos: "verb-u" },
  { lesson: 21, japanese: "みつかる", reading: "みつかる", english: "to be found", pos: "verb-u" },
  { lesson: 21, japanese: "はじまる", reading: "はじまる", english: "to begin; to start (intransitive)", pos: "verb-u" },
  { lesson: 21, japanese: "はじめる", reading: "はじめる", english: "to start; to begin (transitive)", pos: "verb-ru" },
  { lesson: 21, japanese: "おわる", reading: "おわる", english: "to end; to finish (intransitive)", pos: "verb-u" },
  { lesson: 21, japanese: "おわらせる", reading: "おわらせる", english: "to finish; to end (transitive)", pos: "verb-ru" },
  { lesson: 21, japanese: "パソコン", reading: "パソコン", english: "personal computer; PC", pos: "noun" },
  { lesson: 21, japanese: "スマートフォン", reading: "スマートフォン", english: "smartphone", pos: "noun" },
  { lesson: 21, japanese: "タブレット", reading: "タブレット", english: "tablet (device)", pos: "noun" },
  { lesson: 21, japanese: "インターネット", reading: "インターネット", english: "internet", pos: "noun" },
  { lesson: 21, japanese: "ウェブサイト", reading: "ウェブサイト", english: "website", pos: "noun" },
  { lesson: 21, japanese: "メール", reading: "メール", english: "email; mail", pos: "noun" },
  { lesson: 21, japanese: "メッセージ", reading: "メッセージ", english: "message", pos: "noun" },
  { lesson: 21, japanese: "でんわ", reading: "でんわ", english: "telephone; phone call", pos: "noun" },
  { lesson: 21, japanese: "けいたいでんわ", reading: "けいたいでんわ", english: "cell phone; mobile phone", pos: "noun" },
  { lesson: 21, japanese: "カメラ", reading: "カメラ", english: "camera", pos: "noun" },
  { lesson: 21, japanese: "しゃしん", reading: "しゃしん", english: "photo; photograph", pos: "noun" },
  { lesson: 21, japanese: "どうが", reading: "どうが", english: "video; moving image", pos: "noun" },
  { lesson: 21, japanese: "アプリ", reading: "アプリ", english: "app; application", pos: "noun" },
  { lesson: 21, japanese: "パスワード", reading: "パスワード", english: "password", pos: "noun" },
  { lesson: 21, japanese: "いつでも", reading: "いつでも", english: "anytime; always", pos: "adverb" },
  { lesson: 21, japanese: "どこでも", reading: "どこでも", english: "anywhere; everywhere", pos: "adverb" },
  { lesson: 21, japanese: "だれでも", reading: "だれでも", english: "anyone; everybody", pos: "adverb" },
  { lesson: 21, japanese: "なんでも", reading: "なんでも", english: "anything; everything", pos: "adverb" },
  { lesson: 21, japanese: "〜ても", reading: "〜ても", english: "even if; even though", pos: "conjunction" },
  { lesson: 22, japanese: "いらっしゃる", reading: "いらっしゃる", english: "to be; to go; to come (honorific)", pos: "verb-u" },
  { lesson: 22, japanese: "おっしゃる", reading: "おっしゃる", english: "to say (honorific)", pos: "verb-u" },
  { lesson: 22, japanese: "なさる", reading: "なさる", english: "to do (honorific)", pos: "verb-u" },
  { lesson: 22, japanese: "くださる", reading: "くださる", english: "to give (honorific; giver is superior)", pos: "verb-u" },
  { lesson: 22, japanese: "ごらんになる", reading: "ごらんになる", english: "to see; to look at (honorific)", pos: "verb-u" },
  { lesson: 22, japanese: "めしあがる", reading: "めしあがる", english: "to eat; to drink (honorific)", pos: "verb-u" },
  { lesson: 22, japanese: "まいる", reading: "まいる", english: "to go; to come (humble)", pos: "verb-u" },
  { lesson: 22, japanese: "おる", reading: "おる", english: "to be (humble)", pos: "verb-u" },
  { lesson: 22, japanese: "いたす", reading: "いたす", english: "to do (humble)", pos: "verb-u" },
  { lesson: 22, japanese: "もうす", reading: "もうす", english: "to say; to be called (humble)", pos: "verb-u" },
  { lesson: 22, japanese: "いただく", reading: "いただく", english: "to receive; to eat; to drink (humble)", pos: "verb-u" },
  { lesson: 22, japanese: "はいけんする", reading: "はいけんする", english: "to see; to look at (humble)", pos: "verb-irr" },
  { lesson: 22, japanese: "うかがう", reading: "うかがう", english: "to visit; to ask; to hear (humble)", pos: "verb-u" },
  { lesson: 22, japanese: "ぞんじる", reading: "ぞんじる", english: "to know (humble)", pos: "verb-ru" },
  { lesson: 22, japanese: "しごと", reading: "しごと", english: "work; job; occupation", pos: "noun" },
  { lesson: 22, japanese: "かいしゃ", reading: "かいしゃ", english: "company; firm", pos: "noun" },
  { lesson: 22, japanese: "かいぎ", reading: "かいぎ", english: "meeting; conference", pos: "noun" },
  { lesson: 22, japanese: "しょるい", reading: "しょるい", english: "documents; paperwork", pos: "noun" },
  { lesson: 22, japanese: "ほうこくしょ", reading: "ほうこくしょ", english: "report", pos: "noun" },
  { lesson: 22, japanese: "けいかく", reading: "けいかく", english: "plan; project", pos: "noun" },
  { lesson: 22, japanese: "じょうし", reading: "じょうし", english: "boss; superior", pos: "noun" },
  { lesson: 22, japanese: "どうりょう", reading: "どうりょう", english: "colleague; coworker", pos: "noun" },
  { lesson: 22, japanese: "きゃく", reading: "きゃく", english: "guest; customer; visitor", pos: "noun" },
  { lesson: 22, japanese: "おきゃくさん", reading: "おきゃくさん", english: "guest; customer (polite)", pos: "noun" },
  { lesson: 22, japanese: "しゃいん", reading: "しゃいん", english: "company employee", pos: "noun" },
  { lesson: 22, japanese: "ぶちょう", reading: "ぶちょう", english: "department manager; division chief", pos: "noun" },
  { lesson: 22, japanese: "おせわになる", reading: "おせわになる", english: "to be in someone's care; to receive help", pos: "expression" },
  { lesson: 22, japanese: "よろしくおつたえください", reading: "よろしくおつたえください", english: "please give my regards", pos: "expression" },
  { lesson: 22, japanese: "おじゃまします", reading: "おじゃまします", english: "excuse me for intruding (entering a home/office)", pos: "expression" },
  { lesson: 22, japanese: "ただいま", reading: "ただいま", english: "I'm home; right now", pos: "expression" },
  { lesson: 22, japanese: "おかえり", reading: "おかえり", english: "welcome home", pos: "expression" },
  { lesson: 22, japanese: "ていねい", reading: "ていねい", english: "polite; courteous; careful", pos: "na-adj" },
  { lesson: 23, japanese: "〜なければならない", reading: "〜なければならない", english: "must; have to", pos: "expression" },
  { lesson: 23, japanese: "〜てはいけない", reading: "〜てはいけない", english: "must not; may not", pos: "expression" },
  { lesson: 23, japanese: "〜はずだ", reading: "〜はずだ", english: "is supposed to; is expected to", pos: "expression" },
  { lesson: 23, japanese: "〜べきだ", reading: "〜べきだ", english: "should; ought to", pos: "expression" },
  { lesson: 23, japanese: "かんがえる", reading: "かんがえる", english: "to think; to consider", pos: "verb-ru" },
  { lesson: 23, japanese: "しんじる", reading: "しんじる", english: "to believe; to trust", pos: "verb-ru" },
  { lesson: 23, japanese: "守る", reading: "まもる", english: "to protect; to obey (rules)", pos: "verb-u" },
  { lesson: 23, japanese: "こわれる", reading: "こわれる", english: "to break; to be broken", pos: "verb-ru" },
  { lesson: 23, japanese: "かわる", reading: "かわる", english: "to change; to transform", pos: "verb-u" },
  { lesson: 23, japanese: "すすむ", reading: "すすむ", english: "to advance; to progress", pos: "verb-u" },
  { lesson: 23, japanese: "問題", reading: "もんだい", english: "problem; question; issue", pos: "noun" },
  { lesson: 23, japanese: "環境", reading: "かんきょう", english: "environment", pos: "noun" },
  { lesson: 23, japanese: "社会", reading: "しゃかい", english: "society", pos: "noun" },
  { lesson: 23, japanese: "政治", reading: "せいじ", english: "politics", pos: "noun" },
  { lesson: 23, japanese: "けいざい", reading: "けいざい", english: "economy; economics", pos: "noun" },
  { lesson: 23, japanese: "ぶんか", reading: "ぶんか", english: "culture", pos: "noun" },
  { lesson: 23, japanese: "でんとう", reading: "でんとう", english: "tradition; convention", pos: "noun" },
  { lesson: 23, japanese: "へいわ", reading: "へいわ", english: "peace", pos: "noun" },
  { lesson: 23, japanese: "せんそう", reading: "せんそう", english: "war", pos: "noun" },
  { lesson: 23, japanese: "じゆう", reading: "じゆう", english: "freedom; liberty", pos: "noun" },
  { lesson: 23, japanese: "びんぼう", reading: "びんぼう", english: "poverty; poor", pos: "na-adj" },
  { lesson: 23, japanese: "ゆたか", reading: "ゆたか", english: "wealthy; abundant; rich", pos: "na-adj" },
  { lesson: 23, japanese: "たいせつ", reading: "たいせつ", english: "important; precious; valued", pos: "na-adj" },
  { lesson: 23, japanese: "しんぱい", reading: "しんぱい", english: "worry; concern; anxiety", pos: "noun" },
  { lesson: 23, japanese: "きぼう", reading: "きぼう", english: "hope; wish; desire", pos: "noun" },
  { lesson: 23, japanese: "ゆめ", reading: "ゆめ", english: "dream; aspiration", pos: "noun" },
  { lesson: 23, japanese: "しょうらい", reading: "しょうらい", english: "future", pos: "noun" },
  { lesson: 23, japanese: "もくひょう", reading: "もくひょう", english: "goal; target; objective", pos: "noun" },
  { lesson: 23, japanese: "こくさいてき", reading: "こくさいてき", english: "international", pos: "na-adj" },
  { lesson: 23, japanese: "ほんとうに", reading: "ほんとうに", english: "truly; really; indeed", pos: "adverb" },
  { lesson: 23, japanese: "ぜひ", reading: "ぜひ", english: "by all means; definitely", pos: "adverb" },
  { lesson: 23, japanese: "〜のに", reading: "〜のに", english: "even though; despite (regret/criticism)", pos: "conjunction" },
  { lesson: 23, japanese: "〜ために", reading: "〜ために", english: "for the purpose of; because of", pos: "conjunction" }
];

if (typeof module !== 'undefined') {
  module.exports = { GENKI2_VOCAB };
}
